// constants/languages.js

const languages = [
  { label: 'Am English', code: 'english', flag: '🇺🇸' },
  { label: 'Spanish',    code: 'spanish', flag: '🇲🇽' },
  { label: 'French',     code: 'french',  flag: '🇫🇷' },
  { label: 'German',     code: 'german',  flag: '🇩🇪' },
  { label: 'Japanese',   code: 'japanese',flag: '🇯🇵' },
  { label: 'Korean',     code: 'korean',  flag: '🇰🇷' },
  { label: 'Portuguese', code: 'portuguese', flag: '🇵🇹' },
  { label: 'Italian',    code: 'italian', flag: '🇮🇹' },
  { label: 'Dutch',      code: 'dutch',   flag: '🇳🇱' },
  { label: 'Swedish',    code: 'swedish', flag: '🇸🇪' },
  { label: 'Russian',    code: 'russian', flag: '🇷🇺' },
  { label: 'Hindi',      code: 'hindi',   flag: '🇮🇳' },
  { label: 'Arabic',     code: 'arabic',  flag: '🇸🇦' },
  { label: 'Chinese',    code: 'chinese', flag: '🇨🇳' },
  { label: 'Turkish',    code: 'turkish', flag: '🇹🇷' },
  { label: 'Polish',     code: 'polish',  flag: '🇵🇱' },
  { label: 'Vietnamese', code: 'vietnamese', flag: '🇻🇳' },
  { label: 'Thai',       code: 'thai',    flag: '🇹🇭' },
  { label: 'Indonesian', code: 'indonesian', flag: '🇮🇩' },
  { label: 'Hebrew',     code: 'hebrew',  flag: '🇮🇱' },
  { label: 'Ukrainian',  code: 'ukrainian', flag: '🇺🇦' },
  { label: 'Czech',      code: 'czech',   flag: '🇨🇿' },
  { label: 'Hungarian',  code: 'hungarian', flag: '🇭🇺' },
  { label: 'Greek',      code: 'greek',   flag: '🇬🇷' },
  { label: 'Romanian',   code: 'romanian', flag: '🇷🇴' },
  { label: 'Malay',      code: 'malay',   flag: '🇲🇾' },
  { label: 'Finnish',    code: 'finnish', flag: '🇫🇮' },
  { label: 'Danish',     code: 'danish',  flag: '🇩🇰' },
  { label: 'Norwegian',  code: 'norwegian', flag: '🇳🇴' },
  { label: 'Filipino',   code: 'filipino', flag: '🇵🇭' },
];

export default languages;
